server:
  port: 4004

spring:
  cloud:
    gateway:
      routes:
        ## http://localhost:4004/auth/login
        ## API GATEWAY --> http://auth-service:4005/login
        - id: auth-service-route
          uri: http://auth-service:4005
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1


        # Route for /api/patients/** to patient-service
        ## REST CLIENT --> http://localhost:4001/api/patients
        ## API GATEWAY --> http://patient-service:4001/patients
        ## PATIENT SERVICE (SPRING BOOT APP) --> /patients --> Patients Array
        - id: patient-service-route
          uri: http://patient-service:4001
          predicates:
            - Path=/api/patients/**
          filters:
            - StripPrefix=1
            - JwtValidation
#            Matches JwtValidation prefix class having suffix as GatewayFilterFactory i.e. JwtValidationGatewayFilterFactory


        ## REST CLIENT --> http://localhost:4001/api-docs/patients
        ## API-GATEWAY --> http://patient-service:4001/v3/api-docs
        - id: api-docs-patient-route
          uri: http://patient-service:4001
          predicates:
            - Path=/api-docs/patients
          filters:
            - RewritePath=/api-docs/patients,/v3/api-docs


        - id: api-docs-auth-route
          uri: http://auth-service:4005
          predicates:
            - Path=/api-docs/auth
          filters:
            - RewritePath=/api-docs/auth,/v3/api-docs

